<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PronosticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PronosticRepository extends EntityRepository
{
  publicfunction getPronosticsEnCours() {
    $query = $this->getEntityManager()->createQuery("
        SELECT p, r
        FROM \AppBundle\Entity\Pronostic p
        JOIN p, rencontre r
        WHERE r.data> :date
        ORDER BY r.date DESC
        ")->setparameter('date', date('Y-m-d'));
        return $query->getResult();
  }
}
