<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends EntityRepository
{
    function getRencontreByEquipe($nomEquipe) {
      $query = $this->
      getEntityManager()->
      createQuery('
        SELECT r
        FROM \AppBundle\Entity\rencontre r
        WHERE r.equipeA = :nom
        OR r.equipeB = :nom
        ORDER BY r.date ASC
      ')->setParameter('nom', $nomEquipe);

      return $query->getResult();
    }

}
