<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RencontreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RencontreRepository extends EntityRepository
{
  public function getRencotresByEquipe($nomEquipe){
    $query= $this->getEntityManager()->createQuery("
        SELECT r
        FROM \AppBundle\Entity\Rencontre r
        WHERE r.equipeA=:nom OR r.equipeB =:nom
    ")->setParameter('nom',$nomEquipe);
    return $query->getResult();
  }
}
