<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  function getMeilleurPronostiqueur() {
    $query = $this->
    getEntityManager()->
    createQuery('
      SELECT u.username username,
             sum(p.nbCafe)  nbCafe
      FROM AppBundle:Pronostic p
      JOIN p.rencontre r
      JOIN p.utilisateur u
      WHERE
      r.scoreA = p.scoreA
      AND r.scoreB = p.scoreB
      GROUP BY u.username
      ORDER BY p.nbCafe
    ');

    return $query->getResult();
  }
}
